language: python

jobs:
  include:
    - python: '3.6'
      env: NOXSESSIONS="docs test"
    - python: '3.7'  # Also test docs with latest supported python version
      env: NOXSESSIONS="test"
    - python: '3.8'  # Also test docs with latest supported python version
      env: NOXSESSIONS="test"

cache: pip

install:
  - pip install nox
  - pip install coveralls

script:
  - nox --non-interactive -s $NOXSESSIONS

after_success:
  - coveralls

deploy:
  provider: pypi
  user: __token__
  distributions: sdist bdist_wheel
  password: $CITOKEN
  on:
    tags: true